### ISSUE TITLE
Extension fails to import dependencies

### ISSUE THREAD

**Issue by beechnut** [ckan/ckan-docker#12]
I'm getting an `ImportError` using the fairly new [ckanext-dataproxy](https://github.com/cphsolutionslab/ckanext-dataproxy) extension. Any help determining why the requirements aren't available to the extension would be massively appreciated. (I've cross-posted this issue to ckan-dataproxy.)

I cloned the repository in _src/, so my file tree looks like:

![file-tree](https://cloud.githubusercontent.com/assets/1887182/6535824/ece638d4-c415-11e4-9ef2-e9d32e2c7b45.png)

I rebuild the image running `$ docker exec -it fig-ckan fig build --no-cache ckan` and it succeeds.
I run the fig `$ docker exec -it fig-ckan fig up` and it does quite a lot, until it throws [this error](https://gist.github.com/beechnut/2a30e992990bf68333e4).

I run the image, and inspect the `_src` directory:

```
$ docker run -it --rm src_ckan /bin/bash
$ ls /usr/lib/ckan/default/src
README.md  ckan  ckanext-dataproxy  simple-crypt
```

So, ckanext-dataproxy is definitely running `pip install`, because it's copying files to the `_src` directory. So why isn't `from simplecrypt import encrypt` available?

Inside the container, I test whether simplecrypt is available inside and outside of the virtualenv created by the line `RUN virtualenv $CKAN_HOME`, which doesn't itself get activated during the process. 

```
$ echo 'from simplecrypt import encrypt' | python -  # I think this should work, but doesn't.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named simplecrypt

$ virtualenv $CKAN_HOME/

New python executable in /usr/lib/ckan/default/bin/python
Installing setuptools, pip...done.

$ echo 'from simplecrypt import encrypt' | python -  # This probably shouldn't work, and doesn't.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named simplecrypt
```

So, `simplecrypt` is not available anywhere, despite appearing to be installed in `/usr/lib/ckan/default/src`.

I ran `pip_install_req` and got, essentially,

```
Installing collected packages: simple-crypt
  Running setup.py develop for simple-crypt
    Creating /usr/lib/ckan/default/lib/python2.7/site-packages/simple-crypt.egg-link (link to src)
    simple-crypt 3.0.2 is already the active version in easy-install.pth
    Installed /usr/lib/ckan/default/src/simple-crypt/src
Successfully installed simple-crypt
```

But `echo 'from simplecrypt import encrypt' | python -` returned `ImportError: No module named simplecrypt`.

**Comment by allthesignals** [comment]
I'm not sure that [this script](https://github.com/ckan/ckan-docker/blob/master/docker/ckan/pip_install_req.sh) activates the virtualenv at any point? Activating it and pip installing the specific requirement resolves the issue.

**Comment by beechnut** [comment]
Progress: realized everything installs into $CKAN_HOME/bin, via [pip_install_req.sh](https://github.com/ckan/ckan-docker/blob/master/docker/ckan/pip_install_req.sh)?

Running a fresh CKAN container, it's clear that `simplecrypt` is available once activating $CKAN_HOME/bin.

```
$ docker run -it --rm src_ckan /bin/bash
root@47b533eb5f6a:/# echo 'from simplecrypt import encrypt' | python -
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named simplecrypt
root@47b533eb5f6a:/# source /usr/lib/ckan/default/bin/activate
(default)root@47b533eb5f6a:/# echo 'from simplecrypt import encrypt' | python -
(default)root@47b533eb5f6a:/#
```
Still not available to CKAN, though.

**Comment by beechnut** [comment]
Other things that don't work:

- adding `simple-crypt` to the base CKAN `requirements.txt`
- adding the non-git version of `simple-crypt` to the dataproxy `requirements.txt`

**Comment by clementmouchet** [comment]
Can you share your project on github or somewhere else if you want further support?

The scripts you mention do not activate the environment explicitly because it's not needed if you use pip from the environment i.e. $CKAN_HOME/bin/pip

Your commands don't point at it, or activate it. You could active it before executing your command: . $CKAN_HOME/bin/activate

Let me know how it goes, and we'll close the gaps in the documentation in a generic way.

**Comment by beechnut** [comment]
My project is available [here](https://github.com/beechnut/ckan-docker). A simple `fig up` will show the error.

Thanks in advance for the support.

I think my thoughts about "activation" may have been going down the wrong path. In short, my question is: if I've followed the instructions in adding an extension to the _src folder, why are its requirements not installing properly?

**Comment by clementmouchet** [comment]
Had a quick look at that this evening. The version of `simple-crypt` (3.0.2) required is not available in the easy-install.pth as you said because it's not installed in `$CKAN_HOME/src` but in a src folder inside the extension.
That's because loop in `pip_install_req.sh` moves into the extensions folder. You could update it to install requirements from the `$CKAN_HOME/src`, which would solve the issue but the easiest and best option is to clone simple-crypt first in your `_src` folder.

```
git clone https://github.com/andrewcooke/simple-crypt.git
cd simple-crypt
git reset --hard bb8c85128d4fff0d448e524f8acebb99b777cc38
```

That way you'll also keep this version in your favourite version control tool, since it's not in pypi.

In your CKAN docker file, you could consider adding the extra packages as a separate instruction i.e.

```
RUN DEBIAN_FRONTEND=noninteractive apt-get -qq -y install \
        libmysqlclient-dev \
        freetds-dev
```

and in your custom_options file, you need to remove the `pdf_view` plugin which is not part of the core anymore (or clone the extension)

Hope it helps

Cheers,

C

**Comment by beechnut** [comment]
Thanks. This got it up and running. We should probably change the plugin installation instructions to include how to set up git-based `pip installs`, based on this thread.

**Comment by clementmouchet** [comment]
Yes. I also want to add the ability to download requirements upfront in a local pypi repo and use the pipit ---no-index function to speed things up. I've already done it for myself but I think the ability to download them only should be preserved so it needs a bit more work, and I don't have time now... and as far as the documentation is concerned I really think the readme has to move to readthedocs.

Do you want me to reopen the issue?

**Comment by beechnut** [comment]
No need to reopen this one -- I think documentation can be treated as a separate item.
