### ISSUE TITLE
Unhealthy ckan and datapusher containers on installation in development server

### ISSUE THREAD

**Issue by leomunguia** [ckan/ckan-docker#153]
Hello ckan community,

I have a problem with ckan and datapusher containers when I try to deploy a ckan project in development server. After of applicate the command **docker compose up -d** directly in development server it's shows me the following message: 

![image](https://github.com/ckan/ckan-docker/assets/99312438/a98ad0e9-f93a-446d-a04e-ef4c8298a08e)

Also, when I applied the command **docker ps -a** the result is as follows:

![image](https://github.com/ckan/ckan-docker/assets/99312438/bf003a82-da54-4d5e-8cb2-b9e56b5e4cc4)
 
Like I said in the beggining, ckan and datapusher containers are "unhealthy" but only in development server, because in my PC I don´t have problems with this and the project is get up without drawback:

![image](https://github.com/ckan/ckan-docker/assets/99312438/10a7e894-3215-45db-9057-2947906caf52)

I used the 2.10.1 ckan version and 24.0.7 docker engine version in my pc. In development server 26.1.4 . Please help me to resolve this problem.

**Comment by ipimpat** [comment]
Which docker version do you have on your development server?

**Comment by leomunguia** [comment]
I have the 26.1.4 Docker engine version in the development server. In my PC I have 24.0.7 version.

**Comment by kowh-ai** [comment]
Check out [this PR](https://github.com/ckan/ckan-docker-base/pull/67) - it's not merged yet but fixes a problem with Docker v26

**Comment by kumarvivek1752** [comment]
same issue i'm getting for ckan docker dev mode 

```
➜  ckan git:(master) ✗ docker -v               
Docker version 26.1.4, build 5650f9b102
➜  ckan git:(master) ✗ docker compose version                     
Docker Compose version 2.27.2
➜  ckan git:(master) ✗ docker ps               
CONTAINER ID   IMAGE                              COMMAND                  CREATED         STATUS                     PORTS                    NAMES
16357199141a   ckan-ckan-dev                      "/srv/app/start_ckan…"   6 minutes ago   Up 6 minutes (unhealthy)   0.0.0.0:5000->5000/tcp   ckan-ckan-dev-1
db15a7eefbb1   ckan/ckan-solr:2.10-solr9          "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes (healthy)     8983/tcp                 ckan-solr-1
55c5b0253ac7   redis:6                            "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes (healthy)     6379/tcp                 ckan-redis-1
eb483781fcad   ckan-db                            "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes (healthy)     5432/tcp                 ckan-db-1
038a40c08d7b   ckan/ckan-base-datapusher:0.0.20   "sh -c 'uwsgi --plug…"   6 minutes ago   Up 6 minutes (unhealthy)   8800/tcp                 ckan-datapusher-1
➜  ckan git:(master) ✗ 

```
To which version should I downgrade docker?
