### ISSUE TITLE
Problems with adding new datasets to restored CKAN instance on AWS

### ISSUE THREAD

**Issue by Analect** [ckan/ckan-docker#16]
@clementmouchet 
As per the ending comment on #14, I'm working on getting my ckan (previously working under the docker cygri/ckan set-up) working on AWS with this ckan-docker approach.  I'm hitting various obstacles that I can't appear to resolve. There are more moving parts (containers) in this set-up and so some of the troubleshooting I've found on various CKAN forums isn't necessarily helping.

I'm running this on an ubuntu EC2 ...Ubuntu 13.10 (GNU/Linux 3.11.0-15-generic x86_64), although in my efforts to troubleshoot, I have also tried all these things on a local VM with 14.04 installed.

ckan.ini config file: https://gist.github.com/Analect/dbd56d947139fb7936ca
apache error logs: https://gist.github.com/Analect/a7fdea39c60a864fc264
/etc/hosts on ckan container: https://gist.github.com/Analect/3e1ee03ba5184542dc21

Problems:
1. The reindex of datasets (using paster) from ckan container is somehow not persisting. This presumably updates the solr instance, but is that in turn being persisted to the data container?  In this set-up, is the data container mirroring the postgres databases and filestore directory back to the host machine?
2. I'm getting a 'server error' (500) anytime I either manually add a dataset or try to use something like the test code at https://github.com/ckan/example-add-dataset to add a dataset and resource programmatically.  The logs are linked above. There are various moving parts involving nginx, where I'm admittedly lost. I can see from the logs that the localdomain.ckan (172.17.0.97) is referenced, but the main references are to the nginx container (172.17.0.99), where I suspect the problem lies.  Is there any significance that this is the only container that hasn't been appended to /etc/hosts in the ckan container, as per the link above?
3. In the cygri/ckan set-up, where there were only 3 containers (ckan, solr, postgres) you were dealing with, somehow things were easier to troubleshoot.  With the ckan-docker approach ... I'm finding restarting solr or nginx services often inadvertently end up crashing the container and bringing all the containers down.  Could you help me understand the benefits of having a separate dedicated container for nginx and datapusher?  And does having a data container give better protection versus just the postgres container?
4. Are your working set-ups experiencing any of the same problems with SOLR and a 2.3 CKAN instance, as alluded to here: https://github.com/ckan/ckan/issues/1651

Thanks for any pointers / suggestions that may help me resolve.
Colum

**Comment by clementmouchet** [comment]
Looks like the exception is thrown by geoview, I don't think this has anything to do with ckan-docker, will try at home whenever I have time

**Comment by clementmouchet** [comment]
Hi @Analect, did you get to the bottom of this one?
