### ISSUE TITLE
Unhealthy ckan and datapusher containers on deploy a CKAN project in server with AlmaLinux9

### ISSUE THREAD

**Issue by leomunguia** [ckan/ckan-docker#163]
Hello CKAN community,

I tried to deploy a CKAN project in a server with AlmaLinux9 but it's shows me the following:

![image](https://github.com/user-attachments/assets/316bc2f2-d810-47f6-90ce-ff1e6c7a04f2)

The ckan and datapusher containers are both in 'unhealthy' and this give me an error, then I can't work with CKAN. In the AlmaLinux9 server I have the 27.0.3 Docker Engine version and the CKAN version is 2.10.1.

How can I fix this error? Help me please!

Regards!

**Comment by kowh-ai** [comment]
This problem could very well be fixed in the following images:

`ckan/ckan-base:2.10.4`
`ckan/ckan-base-datapusher:0.0.21`

Are you able to try using these?

**Comment by leomunguia** [comment]
Hi, I have used them, however, they have not worked for me. I decided to build the project on Ubuntu 22.04.

Thank you.
