### ISSUE TITLE
start_ckan.sh fails so the Admin User (ckan_admin) is not created

### ISSUE THREAD

**Issue by kowh-ai** [ckan/ckan-docker#171]
The `ckan/ckan-base:2.11.0` base image is used in the ckan Dockerfile. When the `start_ckan.sh` `CMD` script runs when the ckan container starts, it aborts when the database is initialized, so the Admin User (ckan_admin) is not created

Related issue: https://github.com/ckan/ckan-docker/issues/167

![Screenshot 2024-09-04 at 10 53 35 am](https://github.com/user-attachments/assets/c257a07f-6856-4074-9558-0c6502db5bbf)

**Workaround:** use `ckan/ckan-base:2.10.5` as the base image in the ckan Dockerfile or manually create an Admin user as per https://github.com/ckan/ckan-docker/issues/167

**Comment by kowh-ai** [comment]
dev (2.11.0) image works fine and the `ckan db init` command works too

![Screenshot 2024-09-04 at 2 59 16 pm](https://github.com/user-attachments/assets/766751d3-8d19-473b-87e0-e1c021fc2591)

**Comment by amercader** [comment]
OK, I'm making some progress debugging this. When the command execution starts and we call `load_environment()` -> `plugins.load_all()` the plugins loaded are the ones in the ini file. Those were set [here](https://github.com/ckan/ckan-docker-base/blob/b69d2fdd70016627fad6bcbb43f1dec255caf0de/ckan-2.11/base/setup/prerun.py#L21) based on this [envvar](https://github.com/ckan/ckan-docker-base/blob/b69d2fdd70016627fad6bcbb43f1dec255caf0de/ckan-2.11/base/Dockerfile#L16) set in the Dockerfile (which does not have datapusher), not the one in the .env 

We need to do one final test. Do the latest 2.10.5 images work?

* If yes, something changed in the startup logic and need to keep digging
* If no, then it's probably related to the removal of datapusher from the plugins list here https://github.com/ckan/ckan-docker-base/commit/f77c387740a079d25f88fbd9c67a47b163b2f4e7

**Comment by kowh-ai** [comment]
Yes, the 2.10.5 images work - I'll double check to make sure tho

**Comment by amercader** [comment]
I'm pretty sure it's related to this: https://github.com/ckan/ckan/pull/8221

We might need to call `plugins.load_all()` from ckanext-envvars if the `ckan.plugins` setting was changed. Will check it tomorrow.

**Comment by wardi** [comment]
Certainly possible. Maybe there's a better way to prevent going through all the plugins_update logic twice on every startup?

**Comment by amercader** [comment]
If ckanext-envvars adds new plugins we want to load them and also call `update_config()` again (via `load()` -> `plugins_update()`), in case the new plugin needs to update the config too. I've followed this approach in https://github.com/amercader/ckanext-envvars/commit/6a2606af7a94ae8e98ceb96d833f79d02f5a872f and that did solve the issue raised here.

I'm not sure if there's another way to approach this if 1) you need to load the plugins first but 2) these plugins can modify the configuration, including adding new plugins.


I'm now fixing other issues with ckanext-envvars and waiting for https://github.com/okfn/ckanext-envvars/issues/11 to do a new release

**Comment by amercader** [comment]
I've pushed a new ckanext-envvars version (0.0.6) with fixes, update the images to [use that version](https://github.com/ckan/ckan-docker-base/commit/dea74608624495360ff8fdcb9593bd62cf99ad96) and pushed them to the registry.

The issue should now be fixed when pulling, re-building the images:

```
docker pull ckan/ckan-base:2.11.0
docker compose build ckan
```

If using the dev images:

```
docker pull ckan/ckan-dev:2.11.0
docker compose -f docker-compose.dev.yml build ckan-dev
```

You'll need to stop/remove the current `ckan` / `ckan-dev` containers to use the new ones with the latest image.

@kowh-ai can you double test and close the issues if all looks good?

**Comment by kowh-ai** [comment]
All good @amercader - tested fine, thanks
