### ISSUE TITLE
Add a default error.html file to the nginx configuration

### ISSUE THREAD

**Issue by kowh-ai** [ckan/ckan-docker#177]
Related: [PR](https://github.com/ckan/ckan-docker/pull/174)

nginx will serve a 404 when an error occurs as it cannot find an error.html file:

We should add an `error.html` file to the configuration

**Comment by Nisha1293** [comment]
Hi @kowh-ai 
I want to resolve this issue. Do we need to update the custom error page, or is the following error page content sufficient?

error.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<body>
    <h1>Oops! Something went wrong.</h1>
    <p>We're sorry, but the page you requested could not be found.</p>
</body>
</html>
```

If this is okay, I will raise the PR. Please let me know your suggestion.

**Comment by kowh-ai** [comment]
@Nisha1293 - Yes I think this looks OK...please create a PR and I will test it - thanks
