### ISSUE TITLE
Postgres error for vanilla install

### ISSUE THREAD

**Issue by makkus** [ckan/ckan-docker#19]
Hi, 

there seems to be a problem with some of the db creation scripts, I tried to get this working from scratch a few times now, but I always run into the same error (below). All I do is clone the repo, clone ckan into the _src folder, and clone _datapusher in the _service_provicer/_datapusher folder. Then run 'docker-compose build' and 'docker-compose up'. I assume using docker-compose instead of fig should not cause any issues, right?

Anyway, here are the important (error) bits in the output of the first run of 'docker-compose up':

...
...
...
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
solr_1       | 9913 [qtp1786704760-12] INFO  org.apache.solr.core.SolrCore  – [ckan] webapp=/solr path=/select params={fl=*,score&q=*:*&wt=standard&version=2.2&rows=1} hits=0 status=0 QTime=0 
postgres_1   | COMMENT
solr_1       | 9918 [qtp1786704760-13] INFO  org.apache.solr.core.SolrCore  – [ckan] webapp=/solr path=/admin/file/ params={file=schema.xml} status=0 QTime=1 
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | FATAL:  database "datastore" does not exist
ckan_1       | Traceback (most recent call last):
ckan_1       |   File "/usr/lib/ckan/default/bin/paster", line 9, in <module>
ckan_1       |     load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
ckan_1       |     invoke(command, command_name, options, args[1:])
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
ckan_1       |     exit_code = runner.run(args)
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
ckan_1       |     result = self.command()
ckan_1       |   File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 207, in command
ckan_1       |     self._load_config(cmd!='upgrade')
ckan_1       |   File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 147, in _load_config
ckan_1       |     load_environment(conf.global_conf, conf.local_conf)
ckan_1       |   File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 232, in load_environment
ckan_1       |     p.load_all(config)
ckan_1       |   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 134, in load_all
ckan_1       |     load(*plugins)
ckan_1       |   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 166, in load
ckan_1       |     plugins_update()
ckan_1       |   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 116, in plugins_update
ckan_1       |     environment.update_config()
ckan_1       |   File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 361, in update_config
ckan_1       |     plugin.configure(config)
ckan_1       |   File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/plugin.py", line 82, in configure
ckan_1       |     self.legacy_mode = _is_legacy_mode(self.config)
ckan_1       |   File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/plugin.py", line 37, in _is_legacy_mode
ckan_1       |     connection = engine.connect()
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1717, in connect
ckan_1       |     return self._connection_cls(self, **kwargs)
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 59, in __init__
ckan_1       |     self.__connection = connection or engine.raw_connection()
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1786, in raw_connection
ckan_1       |     return self.pool.unique_connection()
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 273, in unique_connection
ckan_1       |     return _ConnectionFairy._checkout(self)
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 630, in _checkout
ckan_1       |     fairy = _ConnectionRecord.checkout(pool)
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 433, in checkout
postgres_1   | COMMENT
ckan_1       |     rec = pool._do_get()
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 949, in _do_get
ckan_1       |     return self._create_connection()
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 278, in _create_connection
ckan_1       |     return _ConnectionRecord(self)
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 404, in __init__
ckan_1       |     self.connection = self.__connect()
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 530, in __connect
ckan_1       |     connection = self.__pool._creator()
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 95, in connect
ckan_1       |     connection_invalidated=invalidated
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
ckan_1       |     reraise(type(exception), exception, tb=exc_tb)
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 89, in connect
ckan_1       |     return dialect.connect(*cargs, **cparams)
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 376, in connect
ckan_1       |     return self.dbapi.connect(*cargs, **cparams)
ckan_1       |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 179, in connect
ckan_1       |     connection_factory=connection_factory, async=async)
ckan_1       | sqlalchemy.exc.OperationalError: (OperationalError) FATAL:  database "datastore" does not exist
ckan_1       |  None None
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
ckan_1       | *** /etc/my_init.d/70_initdb failed with status 1
ckan_1       | 
ckan_1       | *** Killing all processes...
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
postgres_1   | COMMENT
ckandocker_ckan_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping ckandocker_nginx_1...
Stopping ckandocker_postgres_1...
Stopping ckandocker_data_1...
Stopping ckandocker_solr_1...
Stopping ckandocker_datapusher_1...
Exception in thread Thread-1 (most likely raised during interpreter shutdown):%

**Comment by clementmouchet** [comment]
I've can't reproduce this with a vanilla install on a Mac with boot2docker 1.6 and docker-compose 1.2, CKAN 2.3 and the latest datapusher
What environment and versions are you using?

**Comment by makkus** [comment]
Docker version 1.5.0, build a8a31ef
docker-compose 1.2.0
ckan 2.3
and datapusher master branch

all running on a Ubuntu system

I also tried the head of the master branch of the ckan source, but that seems to have the same issue. I'll try to run it on a different system, maybe it's some weirdness on my dev machine.

Just to confirm, I didn't forget any step, right:

 - clone the ckan-docker repo
 - clone the ckan source into _src
 - clone datapusher into _service-provider/_datapusher
 - run 'docker-compose up'

**Comment by makkus** [comment]
Ok, finally figured out what was wrong. I wasn't using the the latest tagged version of datapusher, but the master branch. Once I switched it worked fine. Can be closed, sorry for the noise.
