### ISSUE TITLE
Docker ckan-dev tags 2.9/2.10 failing since latest tags pushed (2.10 - 24c3221637f0,  2.9 - 095615410276 )

### ISSUE THREAD

**Issue by duttonw** [ckan/ckan-docker#192]
Something outside of this repo's version control has occurred and now we have failing cicd builds:

Our cicd jobs extend the image and is now having issues which it did not have yesterday. Nothing has been changed in our repo/workflows and I was able to retrigger it on a passing run which is less than 24hours old.

Passing (Triggered via push 18 hours ago) : https://github.com/qld-gov-au/ckanext-ytp-comments/actions/runs/12005390429/attempts/1
#5 [ckan  1/10] FROM docker.io/ckan/ckan-dev:2.10@sha256:4f8f8a27f72ddc4509e3fc1c8c29b6615b205d04d12922019629e98acbec124c

Failing: https://github.com/qld-gov-au/ckanext-ytp-comments/actions/runs/12005390429
#5 [ckan  1/10] FROM docker.io/ckan/ckan-dev:2.10@sha256:4117dd652dac492431d0c932642c5724882294ea042ec782dc7909ec96f4c45a

2.10
```
#6 [ckan  2/10] RUN mkdir /docker-entrypoint.d
#6 0.443 mkdir: can't create directory '/docker-entrypoint.d': File exists
time="2024-11-26T02:02:10Z" level=warning msg="current commit information was not captured by the build" error="failed to read current commit information with git rev-parse --is-inside-work-tree"
failed to solve: process "/bin/sh -c mkdir /docker-entrypoint.d" did not complete successfully: exit code: 1
#6 ERROR: process "/bin/sh -c mkdir /docker-entrypoint.d" did not complete successfully: exit code: 1
------
 > [ckan  2/10] RUN mkdir /docker-entrypoint.d:
0.443 mkdir: can't create directory '/docker-entrypoint.d': File exists
------

```

2.11
```

#6 [ckan  2/10] RUN mkdir /docker-entrypoint.d
#6 0.179 mkdir: can't create directory '/docker-entrypoint.d': File exists
time="2024-11-26T02:02:09Z" level=warning msg="current commit information was not captured by the build" error="failed to read current commit information with git rev-parse --is-inside-work-tree"
failed to solve: process "/bin/sh -c mkdir /docker-entrypoint.d" did not complete successfully: exit code: 1
#6 ERROR: process "/bin/sh -c mkdir /docker-entrypoint.d" did not complete successfully: exit code: 1
------
 > [ckan  2/10] RUN mkdir /docker-entrypoint.d:
0.179 mkdir: can't create directory '/docker-entrypoint.d': File exists
------
```

Below is the current point in time details of the tag's and hashes as of this momenet this ticket is created https://hub.docker.com/r/ckan/ckan-dev/tags

<html>
<body>
<div class="MuiStack-root css-ffu5ip" data-testid="repotagsTagListItem" style="box-sizing: inherit; display: flex; flex-direction: row; gap: 4px; -webkit-box-align: center; align-items: center; width: 1855px; color: rgb(0, 0, 0); font-family: Roboto, system-ui, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.28px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="MuiBox-root css-1co6c86" style="box-sizing: inherit; background-color: var(--mui-palette-background-paper); border: 1px solid var(--mui-palette-docker-grey-200); border-radius: 2px; padding: 24px; width: 1855px;"><div class="MuiBox-root css-0" style="box-sizing: inherit;"><p class="MuiTypography-root MuiTypography-body2 css-1h662zc" style="box-sizing: inherit; margin: 0px 0px 4px; font-family: Roboto, system-ui, sans-serif; font-weight: 400; font-size: 0.86rem; line-height: 1.333; letter-spacing: 0.02em; color: var(--mui-palette-secondary-main);"><strong style="box-sizing: inherit; font-weight: 500;">TAG</strong></p><div class="MuiStack-root css-50br4x" style="box-sizing: inherit; display: flex; flex-direction: row; gap: 16px;"><div class="MuiStack-root css-1wp09z1" style="box-sizing: inherit; display: flex; flex-direction: column; gap: 8px; flex: 1 1 0%; min-width: 0px;"><div class="MuiStack-root css-hp68mp" style="box-sizing: inherit; display: flex; flex-direction: row; gap: 8px; -webkit-box-align: center; align-items: center;"><p class="MuiTypography-root MuiTypography-body1 MuiTypography-noWrap css-3f6rb1" style="box-sizing: inherit; margin: 0px; font-family: Roboto, system-ui, sans-serif; font-size: 1rem; line-height: 1.429; letter-spacing: 0.02em; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-weight: 500;"><a class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways css-i7kyri" data-testid="navToImage" data-discover="true" href="https://hub.docker.com/layers/ckan/ckan-dev/2.9-v20241125/images/sha256-095615410276c5b311f2888584e73b569754c40366fdf3ae23d41172a13a0ee3?context=explore" style="box-sizing: inherit; margin: 0px; font: inherit; letter-spacing: inherit; text-decoration-line: underline; text-decoration-style: initial; --Link-underlineColor: rgba(var(--mui-palette-primary-mainChannel) / 0.4); text-decoration-color: inherit; text-decoration-thickness: from-font; color: var(--mui-palette-docker-blue-500, #1D63ED);">2.9-v20241125</a></p></div><p class="MuiTypography-root MuiTypography-body2 css-1d9bvuh" data-testid="tagList_lastPushed" style="box-sizing: inherit; margin: 0px; font-family: Roboto, system-ui, sans-serif; font-weight: 400; font-size: 0.86rem; line-height: 1.333; letter-spacing: 0.02em;">Last pushed<span> </span><strong style="box-sizing: inherit; font-weight: 500;"><span data-testid="dateFromContent" class="" aria-label="Nov 26, 2024 at 12:35 am" style="box-sizing: inherit;">11 hours ago</span></strong><span> </span>by<span> </span><a class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways css-i7kyri" data-discover="true" href="https://hub.docker.com/u/amercader" style="box-sizing: inherit; margin: 0px; font: inherit; letter-spacing: inherit; text-decoration-line: underline; text-decoration-style: initial; --Link-underlineColor: rgba(var(--mui-palette-primary-mainChannel) / 0.4); text-decoration-color: inherit; text-decoration-thickness: from-font; color: var(--mui-palette-docker-blue-500, #1D63ED);">amercader</a></p></div><div class="MuiBox-root css-1lo0jx" style="box-sizing: inherit; min-width: 0px; max-width: 50%; margin-left: auto;"><div class="MuiStack-root css-1821gv5" data-testid="copyPullCommandPullCommand" style="box-sizing: inherit; display: flex; flex-direction: column; gap: 8px;"><div class="MuiBox-root css-0" style="box-sizing: inherit;"><div class="MuiBox-root css-10x186r" style="box-sizing: inherit; position: relative;"><div class="MuiBox-root css-rmzqy6" slot="Root" style="box-sizing: inherit; padding: 8px 8px 0px; min-height: 41px; border-radius: 4px; overflow: hidden; color: var(--mui-palette-docker-grey-700, #393F49); background-color: var(--mui-palette-background-secondary, #F9F9FA); border-width: 1px; border-style: solid; border-color: var(--mui-palette-docker-grey-100, #F4F4F6);"><pre class="MuiTypography-root MuiTypography-code-block css-dqspz" style="box-sizing: inherit; margin: 0px 64px 0px 0px; font-size: 0.975em; font-weight: 400; letter-spacing: 0.02em; font-family: &quot;Roboto Mono&quot;; line-height: 1.429; overflow: auto; padding-bottom: 8px;"><div class="MuiStack-root css-1xhj18k" style="box-sizing: inherit; display: flex; flex-direction: row;"><div class="MuiBox-root css-1ihdwgs" style="box-sizing: inherit; white-space: break-spaces; overflow-wrap: break-word; word-break: break-all;">docker pull ckan/ckan-dev:2.9-v20241125</div></div></pre></div><button class="MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-colorPrimary MuiButton-disableElevation MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-colorPrimary MuiButton-disableElevation css-12pib0g" tabindex="0" type="button" name="CopyButton" slot="Root" data-testid="copy-code" style="box-sizing: border-box; -webkit-box-align: center; align-items: center; -webkit-box-pack: center; justify-content: center; -webkit-tap-highlight-color: transparent; outline: 0px; margin: 0px; cursor: pointer; user-select: none; vertical-align: middle; appearance: none; text-decoration: none; font-family: Roboto, system-ui, sans-serif; font-weight: 500; font-size: 1rem; line-height: 1.75; border: 0px; border-radius: var(--mui-shape-borderRadius); transition: background-color 250ms cubic-bezier(0.4, 0, 0.2, 1), box-shadow 250ms cubic-bezier(0.4, 0, 0.2, 1), border-color 250ms cubic-bezier(0.4, 0, 0.2, 1), color 250ms cubic-bezier(0.4, 0, 0.2, 1); color: var(--variant-containedColor); --variant-textColor: var(--mui-palette-primary-main); --variant-outlinedColor: var(--mui-palette-primary-main); --variant-outlinedBorder: rgba(var(--mui-palette-primary-mainChannel) / 0.5); --variant-containedColor: var(--mui-palette-primary-contrastText); --variant-containedBg: var(--mui-palette-primary-main); box-shadow: none; white-space: nowrap; text-transform: none; min-width: 40px; padding: 4px 16px; letter-spacing: 0.28px; background-color: var(--dds-MuiButton-contained-backgroundColor, var(--variant-containedBg)); position: absolute; top: 4px; right: 4px; opacity: 1; display: block;">Copy</button></div></div></div></div></div></div><div class="MuiTableContainer-root css-1p6ntod" data-testid="repotagsImageList-2.9-v20241125" style="box-sizing: inherit; width: 1805px; overflow-x: auto;">
Digest | OS/ARCH | Compressed size
-- | -- | --
095615410276 | linux/amd64 | 602.36 MB

</div></div></div>
</body>
</html>TAG

[2.9-v20241125](https://hub.docker.com/layers/ckan/ckan-dev/2.9-v20241125/images/sha256-095615410276c5b311f2888584e73b569754c40366fdf3ae23d41172a13a0ee3?context=explore)

Last pushed 11 hours ago by [amercader](https://hub.docker.com/u/amercader)

docker pull ckan/ckan-dev:2.9-v20241125
Digest	OS/ARCH
Compressed size
[095615410276](https://hub.docker.com/layers/ckan/ckan-dev/2.9-v20241125/images/sha256-095615410276c5b311f2888584e73b569754c40366fdf3ae23d41172a13a0ee3?context=explore)

linux/amd64

602.36 MB

TAG

[2.9.11](https://hub.docker.com/layers/ckan/ckan-dev/2.9.11/images/sha256-095615410276c5b311f2888584e73b569754c40366fdf3ae23d41172a13a0ee3?context=explore)

Last pushed 11 hours ago by [amercader](https://hub.docker.com/u/amercader)

docker pull ckan/ckan-dev:2.9.11
Digest	OS/ARCH
Compressed size
[095615410276](https://hub.docker.com/layers/ckan/ckan-dev/2.9.11/images/sha256-095615410276c5b311f2888584e73b569754c40366fdf3ae23d41172a13a0ee3?context=explore)

linux/amd64

602.36 MB

TAG

[2.9](https://hub.docker.com/layers/ckan/ckan-dev/2.9/images/sha256-095615410276c5b311f2888584e73b569754c40366fdf3ae23d41172a13a0ee3?context=explore)

Last pushed 11 hours ago by [amercader](https://hub.docker.com/u/amercader)

docker pull ckan/ckan-dev:2.9
Digest	OS/ARCH
Compressed size
[095615410276](https://hub.docker.com/layers/ckan/ckan-dev/2.9/images/sha256-095615410276c5b311f2888584e73b569754c40366fdf3ae23d41172a13a0ee3?context=explore)

linux/amd64

602.36 MB

TAG

[2.10-v20241125](https://hub.docker.com/layers/ckan/ckan-dev/2.10-v20241125/images/sha256-24c3221637f01c874050db770dabb8ad0bbbf70355350669d30bb29f47031155?context=explore)

Last pushed 11 hours ago by [amercader](https://hub.docker.com/u/amercader)

docker pull ckan/ckan-dev:2.10-v20241125
Digest	OS/ARCH
Compressed size
[24c3221637f0](https://hub.docker.com/layers/ckan/ckan-dev/2.10-v20241125/images/sha256-24c3221637f01c874050db770dabb8ad0bbbf70355350669d30bb29f47031155?context=explore)

linux/amd64

704.11 MB

TAG

[2.10.5](https://hub.docker.com/layers/ckan/ckan-dev/2.10.5/images/sha256-24c3221637f01c874050db770dabb8ad0bbbf70355350669d30bb29f47031155?context=explore)

Last pushed 11 hours ago by [amercader](https://hub.docker.com/u/amercader)

docker pull ckan/ckan-dev:2.10.5
Digest	OS/ARCH
Compressed size
[24c3221637f0](https://hub.docker.com/layers/ckan/ckan-dev/2.10.5/images/sha256-24c3221637f01c874050db770dabb8ad0bbbf70355350669d30bb29f47031155?context=explore)

linux/amd64

704.11 MB

TAG

[2.10](https://hub.docker.com/layers/ckan/ckan-dev/2.10/images/sha256-24c3221637f01c874050db770dabb8ad0bbbf70355350669d30bb29f47031155?context=explore)

Last pushed 11 hours ago by [amercader](https://hub.docker.com/u/amercader)

docker pull ckan/ckan-dev:2.10
Digest	OS/ARCH
Compressed size
[24c3221637f0](https://hub.docker.com/layers/ckan/ckan-dev/2.10/images/sha256-24c3221637f01c874050db770dabb8ad0bbbf70355350669d30bb29f47031155?context=explore)

linux/amd64

704.11 MB

**Comment by wardi** [comment]
I do see the directory `/docker-entrypoint.d/` in `ckan/ckan-dev:2.9-v20241125`, even though the `mkdir` command is an https://github.com/ckan/ckan-docker-base/blob/main/ckan-2.9/Dockerfile#L126 `ONBUILD RUN` command which IIUC is a trigger that is only supposed to be run by downstream images.

I'm not sure why we didn't create this directory with a normal `RUN` command and make it part of the image instead of using this `ONBUILD` trigger feature but it seems that *both* are happening for some reason and causing this error.

So we can either:
1. figure out why the image is now being created with the `/docker-entrypoint.d/` directory ( @amercader could this be related to using `DOCKER_BUILDKIT=1` now?)
2. stop using `ONBUILD`, or
3. just use `mkdir -p` like https://github.com/ckan/ckan-docker-base/pull/94

What do you think @duttonw ?

**Comment by amercader** [comment]
I bet is this buildkit bug: https://github.com/moby/buildkit/issues/5486

Any of the options you mention sounds good to me

**Comment by wardi** [comment]
I like option 2. If removing `ONBUILD` fixes the issue then that gets us a simpler Dockerfile at the same time.

**Comment by duttonw** [comment]
its all magic sauce and the use here does not fit the normal usecase given in the docs.  https://docs.docker.com/reference/dockerfile/#onbuild 

I'd say remove ONBUILD, but still leave in mkdir -p for safety.
