### ISSUE TITLE
Log to STDOUT

### ISSUE THREAD

**Issue by beechnut** [ckan/ckan-docker#20]
During deployment, the Dockerfile logs to stdout, making logs visible to `docker logs`. I haven't checked with Apache in a while, but I cannot find the paster logs (serving in development).

I've searched for a while and can't find the answer to this: How can I set paster (and Apache) to log to stdout?

**Comment by wardi** [comment]
This is what we're doing for apache: https://github.com/datacats/datacats/blob/master/docker/web/ckan_default.conf#L14

paster should always be sending its output to stdout.

**Comment by clementmouchet** [comment]
Or you can forward the logs to a specific log files if required.
There are many ways to collect the logs or access them from outside the containers as well.
You could have a look at that for instance. https://logentries.com/doc/docker/
