### ISSUE TITLE
solr container cannot start

### ISSUE THREAD

**Issue by rausial** [ckan/ckan-docker#21]
Hi,

I am getting this message when docker tries to start the solr container just after it building it: 
  Starting ckandocker_solr_1...
  Cannot start container XXXXXXX: [8] System error: not a directory

Am I missing something on the installation, maybe some solr configuration?

If I look at the log, this is what I get:

```
Timestamp: 2015-05-27 20:00:10.340891754 +0000 UTC
Code: System error

Message: not a directory

Frames:

---
0: setupRootfs
Package: github.com/docker/libcontainer
File: rootfs_linux.go@29

---
1: Init
Package: github.com/docker/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@52

---
2: StartInitialization
Package: github.com/docker/libcontainer.(*LinuxFactory)
File: factory_linux.go@223

---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35

---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26

---
5: main
Package: main
File: docker.go@29

---
6: main
Package: runtime
File: proc.go@63

---
7: goexit
Package: runtime
File: asm_amd64.s@2232
```

**Comment by clementmouchet** [comment]
What OS and versions of Docker & docker-compose are you using?
Are you sure that the path to the solr schema is correctly edited in your fig file?
I'm guessing it can't resolve to the file.
