### ISSUE TITLE
Use a specific CKAN version?

### ISSUE THREAD

**Issue by sckott** [ckan/ckan-docker#23]
Is there a way to specify what CKAN version to use?  e.g., say I wanted to install v2.3, how would I do that?  

Thanks!

**Comment by thezelus** [comment]
Hi @sckott 

Just clone whichever version of CKAN you want to deploy in ``` https://github.com/ckan/ckan-docker/tree/master/_src ``` and it should work.

I have tried this with latest version from the trunk (CKAN repository) and 2.4, both seem to be working fine.

**Comment by sckott** [comment]
Thanks, did you do that manually, or in a Dockerfile?

**Comment by thezelus** [comment]
I did it manually on the host machine, but you can always do this in the primary [Dockerfile](https://github.com/ckan/ckan-docker/blob/master/Dockerfile) after it adds the directory to the container.
```
ADD _src/ $CKAN_HOME/src/
ONBUILD ADD _src/ $CKAN_HOME/src/
``` 
Another way to do it is create a bash scrip that clones the desired repositories (CKAN version + extensions) in _src directory and then executes ```docker-compose up```

**Comment by sckott** [comment]
Thanks very much!

**Comment by florianm** [comment]
@sckott another simple way of running ckan as a docker container is [datacats](http://www.datacats.com/), see my [docs](http://govhack2015.readthedocs.org/en/latest/) for a working setup, supports versions.

**Comment by sckott** [comment]
@florianm nice, thanks, give it a try. 

mostly making sure I know how to install diff. versions of CKAN for purposes of testing the R client, and investigating problems users come with
