### ISSUE TITLE
Why there are two repos for ckan docker?

### ISSUE THREAD

**Issue by pimuzzo** [ckan/ckan-docker#24]
Why there are two repos for ckan docker?

https://github.com/ckan/ckan-docker
https://github.com/ckan/ckan/tree/master/contrib/docker/

**Comment by Vanuan** [comment]
The old one (as well as this one) is broken: https://github.com/ckan/ckan/issues/2255
There are some explanations.

**Comment by Vanuan** [comment]
There is no more or less "official" docker image so far.

**Comment by Vanuan** [comment]
There were some pull requests: https://github.com/ckan/ckan/pull/2338
But nobody has taken care of them.
Current "official" image https://hub.docker.com/r/ckan/ckan/ needs tweeking (new ckan requires new solr version)

**Comment by Vanuan** [comment]
Anyway, the nature of CKAN is that it's highly customizable, and there are no runtime extensions.
So you'd have to modify sources anyway. And build your own image.

**Comment by pimuzzo** [comment]
Thank you for your explanations about the current status.
