### ISSUE TITLE
Nginx should wait for CKAN to start

### ISSUE THREAD

**Issue by deniszgonjanin** [ckan/ckan-docker#3]
The CKAN container can take a while to start, as it installs extensions etc... The nginx container starts right away after the CKAN one does, but since CKAN isn't ready it returns a 502.

I don't think there is a simple solution for this with `fig`. I am personally happy running my CKAN dev environments with just one web server, not two. Maybe this could be the default behaviour, and the nginx image can be put in some sort of contrib/ folder, where people could have an example of how to use CKAN with nginx if they need it. Otherwise they would just get apache - or even just `paster serve` for dev environments.

What do you think @clementmouchet ?

**Comment by niko** [comment]
I've got a similar problem: The CKAN container boots before postgres is available. The CKAN container then closes down and I have to start it manually. Should I open a ticket for this?

**Comment by clementmouchet** [comment]
are you using fig and the service definition provided? fig (or docker-compose) should take care of that and bring the containers in order...

**Comment by niko** [comment]
Yes, I'm using docker-compose. After using `docker-compose start` it looks like the Postgres container is running but the DB not yet responding. When starting the CKAN container manually everthing works fine (besides the nginx conainer not having the CKAN containers correct IP address).

**Comment by clementmouchet** [comment]
I've been using fig for the past 4 months and never had those issues. Haven't migrated my stuff to compose yet but I'm surprised to hear those issues...

**Comment by niko** [comment]
I don't think it happens on `docker-compose up` as the containers are built in order. But it's reproducible here on `docker-compose start`.

**Comment by clementmouchet** [comment]
try `docker-compose up --no-recreate` instead

**Comment by niko** [comment]
`docker-compose up --no-recreate` works. Thanks!

Seems like `start` starts the containers asynchronously while `up` starts the contianers one after another.
