### ISSUE TITLE
Getting `The CSRF token is missing` 400 error when creating an organization

### ISSUE THREAD

**Issue by kuhlaid** [ckan/ckan-docker#40]
I'm guessing this is related to https://github.com/ckan/ckan/issues/7095. Currently I'm running CKAN 2.9.7 (the version as of Feb. 14, 2023).

**Comment by amercader** [comment]
CSRF protection was added to 2.10 so either the image tags are wrong or you pulled the wrong image. On CKAN 2.10 this particular error should be fixed when the images are rebuilt tomorrow (after the official release)

**Comment by kuhlaid** [comment]
This seems to be fixed now with v2.10. Thank you.
