### ISSUE TITLE
`CKAN_SITE_URL` not working as ckan:5000

### ISSUE THREAD

**Issue by kuhlaid** [ckan/ckan-docker#41]
https://github.com/ckan/ckan-docker/blob/5d03530b5142e262de460d5188d82cb8fc119b7a/.env#L33

This should probably default to `CKAN_SITE_URL=http://localhost:5000` for local use.

Also, there are some environment variables such as `CKAN___API_TOKEN__JWT__ENCODE__SECRET` and `CKAN___API_TOKEN__JWT__DECODE__SECRET` that are not being used anywhere in CKAN or the Docker configurations from what I can tell. Is this part of the reason the tokens are failing on the API?

**Comment by kowh-ai** [comment]
re: `CKAN_SITE_URL=http://localhost:5000` yeah you are probably right. Iv'e added a line in the README now mentioning to add `ckan` as a alias to `localhost` if you want to access CKAN by **not** using the NGINX server/container. If it's too confusing for people I'll change the default to localhost as you suggest...

**Comment by kowh-ai** [comment]
re: secret tokens, please see the following advisory: https://github.com/ckan/ckan/security/advisories/GHSA-pr8j-v4c8-h62x
