### ISSUE TITLE
Not possible to change port in dev mode

### ISSUE THREAD

**Issue by kjoshi** [ckan/ckan-docker#43]
I'd like to run CKAN locally on a different port, since port 5000 conflicts with some [macOS AirPlay stuff](https://developer.apple.com/forums/thread/682332) that also runs on port 5000 by default.

I've tried updating the port to 5999 in `.env`:
```
> cat .env | grep '5999'
CKAN_PORT_HOST=5999
CKAN_SITE_URL=http://localhost:5999
CKAN_PORT=5999
CKAN_PORT_HOST=5999
```
and also in the `UWSGI_OPTS` in the `ckan/setup/start_ckan.sh` script.

But after starting the `ckan-dev` container the logs show that CKAN is still running on port 5000:
```
> docker compose -f docker-compose.dev.yml logs ckan-dev -f
...
ckan  | 2023-02-20 10:17:24,236 INFO  [ckan.cli.server] Running CKAN on http://0.0.0.0:5000
```

and the `ckan.ini` in the container still has references to port 5000:
```
> docker compose -f docker-compose.dev.yml exec ckan-dev sh -c "cat ckan.ini | grep 5000"

ckan.devserver.port = 5000
ckan.site_url = http://127.0.0.1:5000
```

Is there another place that I need to update the port to get CKAN to run on a port different to 5000?

**Comment by kowh-ai** [comment]
I think you would need to create your own base image (similar to `ckan/ckan-base:ckan-2.10.0-dev`) and reference that image from the `Dockerfile.dev` file _or_  build a local image from scratch.

**Comment by kowh-ai** [comment]
Actually what would work (and a lot easier) is:

- create a `start_ckan_development.sh` file in the `setup/` directory (copy from the `https://github.com/ckan/ckan-docker-base` repo) and change the last line to be: `sudo -u ckan -EH ckan -c $CKAN_INI run -H 0.0.0.0 --port 5999`

- add the line `COPY setup/start_ckan_development.sh ${APP_DIR}` to the `Dockerfile.dev` file

- change the docker-compose.dev.yml file 
 `healthcheck:`
       `test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:5999  "]`

Iv'e just tried it and it works fine

**Comment by AlasdairGray** [comment]
It would be good to document the port clash in the docker installation instructions. I disabled airplay service but if the above instructions work they should be included somewhere in the installation instructions.
