### ISSUE TITLE
Unable to add custom extensions in production setup

### ISSUE THREAD

**Issue by mirashah** [ckan/ckan-docker#44]
I am able to add a custom extension in the dev environment (i.e. by running docker-compose.dev.yml), but unable to load the same extension in the production environment. I have tried the following steps:

1. Modify ckan.plugins in config using .env file
2. Enter running ckan container
3. Clone repo and install extension from source
4. Run ./start_ckan.sh 

I have verified that the extension was loaded using /api/3/action/status_show, but it still does not appear to be running my extension (not using custom templates).

Am I missing any steps?

**Comment by kowh-ai** [comment]
@mirashah - is your custom extension in a public repo? Maybe I could try to install it....
