### ISSUE TITLE
Docker configuration after remove

### ISSUE THREAD

**Issue by fiedzback** [ckan/ckan-docker#45]
Hi, i am accidentally delete ckan container in docker. And then i re-create container ckan, but cannot start. Logs says cannot connect database. Where i can set the database connection in docker?

**Comment by kowh-ai** [comment]
The database connection used is in the `.env` file. The line you should be looking at is `CKAN_SQLALCHEMY_URL=postgresql://ckan:ckan@db/ckan` This is the connection string that CKAN uses to connect to the "**ckan**" database running on the "**db**" container
