### ISSUE TITLE
Docker Hub plans changes

### ISSUE THREAD

**Issue by amercader** [ckan/ckan-docker#46]
On March 14th 2023 Docker sent the following email:

> Docker is sunsetting Free Team organizations
>
> Free Team organizations are a legacy subscription tier that no longer exists. This tier included many of the same features, rates, and functionality as a paid Docker Team subscription.
> 
> After reviewing the list of accounts that are members of legacy Free Team organizations, we’ve identified yours as potentially being one of them.
> 
> If you own a legacy Free Team organization, access to paid features — including private repositories — will be suspended on April 14, 2023 (11:59 pm UTC). Upgrade your subscription before April 14, 2023 to continue accessing your organization.
> 
> If you don’t upgrade to a paid subscription, Docker will retain your organization data for 30 days, after which it will be subject to deletion. During that time, you will maintain access to any images in your public repositories, though rate limitations will apply. At any point during the 30-day period, you can restore access to your organization account if you upgrade to a paid subscription. Visit our [FAQ](https://em.docker.com/NzkwLVNTQi0zNzUAAAGKf9zNXWIoutHuPI4c_GTN19ijWKf2XOmbifwy3qhbYx3k8HmThNdir6cQWCq2tAvDgNvU1XpPuEHaNEw=) for more information.

Paid plans start at 30$/month which is too expensive for what we use it for so I'd suggest

 1. Apply for the Docker [Open source program](https://www.docker.com/community/open-source/application/): looks like is very restrictive but CKAN as a project would have a chance to be approved
 2. In any case, start pushing the images to the [Github Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) (or a better alternative?) in case CKAN is not approved and in any case, to have an alternative registry anyway.

Any thougths?

**Comment by kowh-ai** [comment]
Thanks @amercader - Yes research what we need to do

**Comment by kowh-ai** [comment]
![Screenshot 2023-03-25 at 10 26 32 am](https://user-images.githubusercontent.com/54408245/227644750-46da7ceb-68e6-4d72-9920-acb510368e16.png)
