### ISSUE TITLE
ckan/ckan docker run error

### ISSUE THREAD

**Issue by gortaisg** [ckan/ckan-docker#5]
Hi,

I managed to run ckan/ckan image last week, on friday If I remember correctly. In 5 minutes, I got ckan running.
But I've tried again today (the same way) and I got an error while trying to do a build run of ckan/ckan image.
Here is the error I got : "SOLR schema version not supported: 2.0. Supported versions are [2.3]
**\* /etc/my_init.d/70_initdb failed with status 1"

ckan/solr and ckan/postgresql run well.

I've seen you made some changes in the past two days... Any idea what goes wrong now ?

Thanks.

**Comment by fterrier** [comment]
I had the same problem following the instructions in http://docs.ckan.org/en/latest/maintaining/installing/install-using-docker.html 
```
$ docker run -d --name db ckan/postgresql
$ docker run -d --name solr ckan/solr
$ docker run -d -p 80:80 --link db:db --link solr:solr ckan/ckan
```

**Comment by clementmouchet** [comment]
Hi @fterrier, as  I said, you are referring to the old images, nior ckan-docker
