### ISSUE TITLE
Add reference of "create user"

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan-docker#61]
There is no reference of create user in README.md

**Comment by Gauravp-NEC** [comment]
@kowh-ai , Please let me know your opinion on this issue.

**Comment by kowh-ai** [comment]
No there isn't but there is already a default user created in the ckan container ie: [create user](https://github.com/ckan/ckan-docker-base/blob/main/ckan-2.10/base/setup/prerun.py#L160) plus the [official documentation](https://docs.ckan.org/en/latest/maintaining/cli.html#user-create-and-manage-users) available

**Comment by Gauravp-NEC** [comment]
> No there isn't but there is already a default user created in the ckan container ie: [create user](https://github.com/ckan/ckan-docker-base/blob/main/ckan-2.10/base/setup/prerun.py#L160) plus the [official documentation](https://docs.ckan.org/en/latest/maintaining/cli.html#user-create-and-manage-users) available

@kowh-ai , Thanks for your quick response.

There is only a default user created in the CKAN container, but to create other user's there is no information in the README.md
There should be docker container command like for example `docker exec -it ckan /usr/local/bin/ckan -c /etc/ckan/ckan.ini sysadmin add johndoe`  for creation of other users. This information is not available in the offical doc: https://docs.ckan.org/en/latest/maintaining/cli.html#user-create-and-manage-users

**Comment by kowh-ai** [comment]
You have specifically used a command issued on the host. There are multiple ways to add a new user in a docker environment

1. run the command on the host
2. run the command within the ckan container
3. Update one of the initialisation scripts eg: `start_ckan.sh` or `prerun.py`

**Comment by Gauravp-NEC** [comment]
> You have specifically used a command issued on the host. There are multiple ways to add a new user in a docker environment
> 
> 1. run the command on the host
> 2. run the command within the ckan container
> 3. Update one of the initialisation scripts eg: `start_ckan.sh` or `prerun.py`

@kowh-ai , Thanks for quick response.

I think we should have all the three ways to add a new user in a docker environment mentioned in document as well. Please let me know your opinion.

**Comment by kowh-ai** [comment]
Sure, create a PR and plenty of detail please

**Comment by Gauravp-NEC** [comment]
> Sure, create a PR with plenty of detail please

@kowh-ai , Thanks for confirmation.

**Comment by Gauravp-NEC** [comment]
> 3. Update one of the initialisation scripts eg: `start_ckan.sh` or `prerun.py`

@kowh-ai , Did you mean to update the files i.e., `prerun.py.override` and ` start_ckan.sh.override` located at https://github.com/ckan/ckan-docker/tree/master/ckan/setup?

I think its enough to mention below two ways for user creation, Please let me know your opinion. Thanks

1. run the command on the host
2. run the command within the ckan container

**Comment by kowh-ai** [comment]
Yes! Please take a look at: https://github.com/ckan/ckan-docker#5-ckan-images

I think all 3 options are valid and should be included in any addition to documentation

**Comment by Gauravp-NEC** [comment]
@kowh-ai , I have raised the PR https://github.com/ckan/ckan-docker/pull/68 to fix this issue. Please have a look. Thanks :)
