### ISSUE TITLE
DB connection does not work with Xloader-Replacement-Wiki-Entry

### ISSUE THREAD

**Issue by stefina** [ckan/ckan-docker#69]
Thanks a lot for providing the guide to add xloader to the setup. I ran into some issues and broke the default setup by applying the suggested changes in the `.env`.
I had to make following changes on top of the ones you already mentioned, so maybe you can verify my suggested changes are valid and add them to the documentation if they apply.
But then, longterm it might be worthwhile to use the ENV-values in the initialization-scripts, too. For the Dockerfile I included two versions, but haven't had time to test the environment-variable version, yet.

`postgresql/Dockerfile`:
```
ENV POSTGRES_USER ckandbuser
```
or 
```
ENV POSTGRES_DB ${POSTGRES_DB}
ENV POSTGRES_USER ${CKAN_DB_USER}
```

`10_create_datastore.sql`
```
CREATE DATABASE ckan_test OWNER ckandbuser ENCODING 'utf-8';
CREATE DATABASE datastore_test OWNER ckandbuser ENCODING 'utf-8';
```

`20_setup_test_databases.sql`
```
CREATE DATABASE datastore OWNER ckandbuser ENCODING 'utf-8';
```

**Comment by kowh-ai** [comment]
Oh I’m so sorry….the WIKI article is based on my current ckan-docker environment which includes a PR (https://github.com/ckan/ckan-docker/pull/59) that Iv’e been waiting to get merged for weeks now. I’m hoping the reviewer/approver will get this completed soon. The PR is an attempt to get this repo more secure. It’s the first of a couple of security PR’s I have lined up.

I’ll update the WIKI article to make sure this doesn’t cause any more confusion. Apologies again @stefina

**Comment by stefina** [comment]
No worries at all! Appreciate your guide a lot, just wanted to make you aware of it so others won't have to debug the issue again. 😃 
And whoooop, thanks a lot for the update, will try it later today 🎉  Will close this issue, in case we find something else, we can re-open or open another issue.
