### ISSUE TITLE
Add Copying and License 

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan-docker#77]
There is no information regarding `Copying and License` in this repo like we have in CKAN (https://github.com/ckan/ckan#copying-and-license) and other repositories (https://github.com/ckan/datapusher#license)

**Comment by Gauravp-NEC** [comment]
@kowh-ai , Please let me know your opinion on this issue. I am interest to submit a PR.

**Comment by kowh-ai** [comment]
> @kowh-ai , Please let me know your opinion on this issue. I am interest to submit a PR.

Sure, please do

**Comment by Gauravp-NEC** [comment]
> > @kowh-ai , Please let me know your opinion on this issue. I am interest to submit a PR.
> 
> Sure, please do

Thanks for confirmation. I will submit a PR.

**Comment by Gauravp-NEC** [comment]
@kowh-ai , I have raised the PR https://github.com/ckan/ckan-docker/pull/79. Please have a look. Thanks:)
