### ISSUE TITLE
Clarification on docker install needed

### ISSUE THREAD

**Issue by Vanuan** [ckan/ckan-docker#8]
Could somebody point me out the relationships between these:

* https://registry.hub.docker.com/u/cygri/ckan/
* https://registry.hub.docker.com/u/ckan/ckan/
* https://github.com/ckan/ckan-docker
* https://github.com/ckan/ckan/tree/master/contrib/docker
* https://github.com/ckan/ckan/blob/master/doc/maintaining/installing/install-using-docker.rst

**Comment by clementmouchet** [comment]
Hi @Vanuan,

ckan-docker is a separate project, it's designed as a flexible boilerplate so that re-users can build and tweak the docker images to use community and custom extensions easily.

The first two in the list are based on the 4th element of the list. and the doc is also related to those.
