### ISSUE TITLE
2.2 support

### ISSUE THREAD

**Issue by niryuu** [ckan/ckan-docker#9]
I'm trying CKAN 2.2 to work on ckan-docker.
But it don't work because it depend on new feature after 2.2.

2.2 uses sed to write config related to docker.
https://github.com/ckan/ckan/blob/26fb24c055efe99aaf122599f8c619eb4dfc1d31/contrib/docker/my_init.d/50_configure
And master(and ckan-docker) uses paster config-tool.
https://github.com/ckan/ckan/blob/master/contrib/docker/my_init.d/50_configure

I'm fighting against sed but it doesn't write settings anymore.
Does anyone have idea?

**Comment by clementmouchet** [comment]
We could probably implement sed as a fallback if the config-tool command fails. I would also like ckan-docker to support 2.2.1

The other thing that would be good is to swich all the baseimages to the official ubuntu ones (trusted)
This means you could easyly change it to run 12.04. Should be fairly straightforward, we just need to write a shell script that runs the myinitd scripts, and call supervisor to manage the jobs. Most of it is here already. cron and sshd would have to be added.
I don't have time for that in the near future though...

**Comment by beechnut** [comment]
:+1: on this issue -- I had to downgrade to 2.2.1 and ran into the same. I'm exploring it to see what I can come up with.

**Comment by niryuu** [comment]
I'm writing python script to execute sed with appropriate options for replace.

**Comment by clementmouchet** [comment]
Thanks guys! Wondered how hard it would be to implement config-tool for CKAN 2.x as a fallback.
